// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3KI3OGPz12n8-etaE2_s8GMWn4eg9BZ8',
    appId: '1:282256712082:web:a99daf215b2bf171e7a14b',
    messagingSenderId: '282256712082',
    projectId: 'motorent-d094c',
    authDomain: 'motorent-d094c.firebaseapp.com',
    storageBucket: 'motorent-d094c.firebasestorage.app',
    measurementId: 'G-PFBQ36ZFGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJQUb-X9JS1_77IDW2uvYiM4z_4KdZz7E',
    appId: '1:282256712082:android:17d06130c635bab6e7a14b',
    messagingSenderId: '282256712082',
    projectId: 'motorent-d094c',
    storageBucket: 'motorent-d094c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA55071DEssK7K6Nwmr9151nHPp_jDosUE',
    appId: '1:282256712082:ios:5036f62cfc3d8ddde7a14b',
    messagingSenderId: '282256712082',
    projectId: 'motorent-d094c',
    storageBucket: 'motorent-d094c.firebasestorage.app',
    iosBundleId: 'com.example.motorent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA55071DEssK7K6Nwmr9151nHPp_jDosUE',
    appId: '1:282256712082:ios:5036f62cfc3d8ddde7a14b',
    messagingSenderId: '282256712082',
    projectId: 'motorent-d094c',
    storageBucket: 'motorent-d094c.firebasestorage.app',
    iosBundleId: 'com.example.motorent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3KI3OGPz12n8-etaE2_s8GMWn4eg9BZ8',
    appId: '1:282256712082:web:7f307af7d8e882c8e7a14b',
    messagingSenderId: '282256712082',
    projectId: 'motorent-d094c',
    authDomain: 'motorent-d094c.firebaseapp.com',
    storageBucket: 'motorent-d094c.firebasestorage.app',
    measurementId: 'G-FLZXECH9L3',
  );
}
